language: node_js
services:
  - mongodb
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
  - "4"
before_script:
  - npm install
notifications:
  email:
    - vic@smalldata.tech
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
