language: node_js
services:
  - mongodb
node_js:
  - "6.1"
  - "4.4"
before_script:
  - npm install
notifications:
  email:
    - victorparmar@gmail.com
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

